# Generated by Django 6.0.6 on 2026-06-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Project ID', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('construction', 'Construction'), ('infrastructure', 'Infrastructure'), ('engineering', 'Engineering'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
