# Generated by Django 6.0.6 on 2026-06-12 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cbs', '0003_monthlypv'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='projects.project')),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('project', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PeriodProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('start', models.DateField(blank=True, null=True)),
                ('finish', models.DateField(blank=True, null=True)),
                ('actual_qty', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ev', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ac', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('etc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('eac', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='monthly.period')),
                ('work_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_progress', to='cbs.workpackage')),
            ],
            options={
                'ordering': ['work_package__control_account__code', 'work_package__code'],
                'unique_together': {('period', 'work_package')},
            },
        ),
    ]
