# Generated by Django 6.0.6 on 2026-06-13 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs', '0004_workpackage_is_cost_activity'),
        ('monthly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVMMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ac', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pv_cumulative', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cpi', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('spi', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('control_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evm_metrics', to='cbs.cbscontrolaccount')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evm_metrics', to='monthly.period')),
            ],
            options={
                'ordering': ['period', 'control_account__code'],
                'unique_together': {('control_account', 'period')},
            },
        ),
    ]
