# Generated by Django 6.0.6 on 2026-06-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly', '0002_evmmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='evmmetric',
            name='ac_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='evmmetric',
            name='ev_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
