# Generated by Django 6.0.6 on 2026-06-12 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBSProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_groups', to='projects.project')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('project', 'code')},
            },
        ),
        migrations.CreateModel(
            name='CBSControlAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_accounts', to='cbs.cbsprojectgroup')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('project_group', 'code')},
            },
        ),
    ]
