# Generated by Django 6.0.6 on 2026-06-12 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bl_start', models.DateField(blank=True, null=True)),
                ('bl_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_packages', to='cbs.cbscontrolaccount')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('control_account', 'code')},
            },
        ),
    ]
