# Generated by Django 6.0.6 on 2026-06-12 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs', '0002_workpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='First day of the month this PV applies to')),
                ('pv', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pv_cumulative', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('control_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_pv', to='cbs.cbscontrolaccount')),
            ],
            options={
                'ordering': ['period'],
                'unique_together': {('control_account', 'period')},
            },
        ),
    ]
