# Generated by Django 6.0.6 on 2026-06-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs', '0003_monthlypv'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage',
            name='is_cost_activity',
            field=models.BooleanField(default=False),
        ),
    ]
